.TH "alglib::errors" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alglib::errors \- Namespace for errors in the AlgLib library\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr const char * \fBkItemNotFound\fP {'Item not found\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBkIndexOutOfRange\fP {'Index out of range\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBkEmptyDeletion\fP {'Cannot delete from empty object\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBkObjectFull\fP {'Object full\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBkObjectEmpty\fP {'Object empty\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBkPeekAtEmpty\fP {'Cannot peek at empty objects\&.'}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Namespace for errors in the AlgLib library\&. 
.SH "Variable Documentation"
.PP 
.SS "const char* alglib::errors::kEmptyDeletion {'Cannot delete from empty object\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB49\fP of file \fBconstants\&.h\fP\&.
.SS "const char* alglib::errors::kIndexOutOfRange {'Index out of range\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB48\fP of file \fBconstants\&.h\fP\&.
.SS "const char* alglib::errors::kItemNotFound {'Item not found\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB47\fP of file \fBconstants\&.h\fP\&.
.SS "const char* alglib::errors::kObjectEmpty {'Object empty\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB51\fP of file \fBconstants\&.h\fP\&.
.SS "const char* alglib::errors::kObjectFull {'Object full\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB50\fP of file \fBconstants\&.h\fP\&.
.SS "const char* alglib::errors::kPeekAtEmpty {'Cannot peek at empty objects\&.'}\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB52\fP of file \fBconstants\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
