.TH "Include/array_stack.h" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/array_stack.h
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include 'constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBalglib::ArrayStack< T, capacity >\fP"
.br
.RI "Template based stack implementation that uses an array as a base structure\&. It doesn't allocate memory on the heap, but it has a fixed capacity that has to be defined at compile time\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalglib\fP"
.br
.RI "Default namespace for the AlgLib library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
