.TH "Include/circular_queue.h" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/circular_queue.h
.SH SYNOPSIS
.br
.PP
\fR#include <array>\fP
.br
\fR#include <stdexcept>\fP
.br
\fR#include 'constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBalglib::CircularQueue< T, capacity >\fP"
.br
.RI "\fBCircularQueue\fP class is a queue data structure implemented using an array\&. It doesn't allocate memory on the heap and has a fixed capacity that has to be defined at compile time\&. It uses a circular buffer to store elements\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalglib\fP"
.br
.RI "Default namespace for the AlgLib library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
