.TH "Include/constants.h" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/constants.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalglib\fP"
.br
.RI "Default namespace for the AlgLib library\&. "
.ti -1c
.RI "namespace \fBalglib::errors\fP"
.br
.RI "Namespace for errors in the AlgLib library\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kItemNotFound\fP {'Item not found\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kIndexOutOfRange\fP {'Index out of range\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kEmptyDeletion\fP {'Cannot delete from empty object\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kObjectFull\fP {'Object full\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kObjectEmpty\fP {'Object empty\&.'}"
.br
.ti -1c
.RI "constexpr const char * \fBalglib::errors::kPeekAtEmpty\fP {'Cannot peek at empty objects\&.'}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
