.TH "Include/sll_stack.h" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/sll_stack.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdexcept>\fP
.br
\fR#include 'constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBalglib::SLLStack< T >\fP"
.br
.RI "\fBSLLStack\fP is a stack implementation that uses a singly linked list as a base structure\&. It allocates memory on the heap, so the stack can grow dynamically\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalglib\fP"
.br
.RI "Default namespace for the AlgLib library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
