.TH "Include/sll_queue.h" 3 "Version 1.0.0" "AlgLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Include/sll_queue.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdexcept>\fP
.br
\fR#include 'constants\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBalglib::SLLQueue< T >\fP"
.br
.RI "\fBSLLQueue\fP class is a queue data structure implemented using singly linked list\&. It allocates nodes on the heap\&. Queue can grow dynamically\&. There is no limit to the amount of elements besides the memory available\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBalglib\fP"
.br
.RI "Default namespace for the AlgLib library\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AlgLib from the source code\&.
